**REAL DATASET BASELINE MODELS**

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

print("Baseline notebook ready.")

Baseline notebook ready.


In [ ]:
df = pd.read_csv(
    "/content/drive/MyDrive/Real_school_data_with_proxy.csv"
)

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (1000, 46)

Columns:
['Student ID', 'School', 'Gender', 'Class level', 'Parental educational level', 'Week1_attendance', 'Week2_attendance', 'Week3_attendance', 'Week4_attendance', 'Week5_attendance', 'Week6_attendance', 'Week7_attendance', 'Week8_attendance', 'Week9_attendance', 'Week10_attendance', 'Week11_attendance', 'Week12_attendance', 'Week13_attendance', 'Week14_attendance', 'Semester 1 average', 'Semester 2 average', 'Semester difference', 'Household income level', 'Family dropout history', 'Child labor involvement', 'Travel time to school', 'Mode of transport', 'Teacher relationship quality', 'Peer relationship quality', 'Extra-curricular activities', 'Section', 'Household income level (standardized)', 'Travel time to school (minutes)', 'grade_number', 'stream_letter', 'subgroup', 'level_prefix', 'long_commute_flag', 'long_walk_flag', 'academic_domain', 'attendance_domain', 'socioeconomic_domain', 'engagement_domain', 'accessibility_domain', 'risk_score', 'drop

In [ ]:
target_column = "dropout_risk"

X = df.drop(columns=[
    "Student ID",
    "risk_score",
    target_column
])

y = df[target_column]

print("Feature matrix shape:", X.shape)
print("Target shape:", y.shape)

print("\nTarget distribution:")
print(y.value_counts().sort_index())

Feature matrix shape: (1000, 43)
Target shape: (1000,)

Target distribution:
dropout_risk
0    250
1    500
2    250
Name: count, dtype: int64


In [ ]:
print("Numerical columns:")
print(X.select_dtypes(include=np.number).columns.tolist())

print("\nCategorical columns:")
print(X.select_dtypes(exclude=np.number).columns.tolist())

Numerical columns:
['Week1_attendance', 'Week2_attendance', 'Week3_attendance', 'Week4_attendance', 'Week5_attendance', 'Week6_attendance', 'Week7_attendance', 'Week8_attendance', 'Week9_attendance', 'Week10_attendance', 'Week11_attendance', 'Week12_attendance', 'Week13_attendance', 'Week14_attendance', 'Semester 1 average', 'Semester 2 average', 'Semester difference', 'Household income level', 'Travel time to school (minutes)', 'grade_number', 'subgroup', 'long_commute_flag', 'long_walk_flag', 'academic_domain', 'attendance_domain', 'socioeconomic_domain', 'engagement_domain', 'accessibility_domain']

Categorical columns:
['School', 'Gender', 'Class level', 'Parental educational level', 'Family dropout history', 'Child labor involvement', 'Travel time to school', 'Mode of transport', 'Teacher relationship quality', 'Peer relationship quality', 'Extra-curricular activities', 'Section', 'Household income level (standardized)', 'stream_letter', 'level_prefix']


In [ ]:
for col in X.select_dtypes(exclude=np.number).columns:
    print(f"\n{col}")
    print("Number of unique values:", X[col].nunique())
    print("Values:", X[col].dropna().unique())


School
Number of unique values: 3
Values: ['Shining Star Preparatory' 'Weweso MA' 'Ayeduase RC']

Gender
Number of unique values: 2
Values: ['Female' 'Male']

Class level
Number of unique values: 21
Values: ['4A' '4B' '7B3' '5' '6B' '5A' '5B' '5B2' '4' 'JHS 1' '6A' 'JHS 1B1' '7B2'
 '6B2' '6' 'JHS 2' '5B1' '4B2' 'JHS 1B2' '4B1' '7B1']

Parental educational level
Number of unique values: 3
Values: ['SHS' 'Tertiary' 'JHS']

Family dropout history
Number of unique values: 3
Values: ['No' 'Yes' 'Not sure']

Child labor involvement
Number of unique values: 3
Values: ['No' 'Yes' 'Sometimes']

Travel time to school
Number of unique values: 79
Values: ['21 minutes' '2 Minutes' '4 minutes' '30 minutes' '3 minutes' '5min'
 '15 minutes' '9min' '1 hour' '30 Minutes' '35 minutes' '5 minutes' '1hr'
 '20 minutes' '50min' '40 minutes' '60 minutes' '1 Hour' '36 minutes'
 '30mins' '2 minutes' '25 minutes' '6 minutes' '80min' '10min'
 '55 minutes' '7 minutes' '120 minutes' '30min' '87 minutes' '20 Minute

In [ ]:
print("Number of columns:", len(df.columns))

for i, col in enumerate(df.columns):
    print(i, ":", col)

Number of columns: 46
0 : Student ID
1 : School
2 : Gender
3 : Class level
4 : Parental educational level
5 : Week1_attendance
6 : Week2_attendance
7 : Week3_attendance
8 : Week4_attendance
9 : Week5_attendance
10 : Week6_attendance
11 : Week7_attendance
12 : Week8_attendance
13 : Week9_attendance
14 : Week10_attendance
15 : Week11_attendance
16 : Week12_attendance
17 : Week13_attendance
18 : Week14_attendance
19 : Semester 1 average
20 : Semester 2 average
21 : Semester difference
22 : Household income level
23 : Family dropout history
24 : Child labor involvement
25 : Travel time to school
26 : Mode of transport
27 : Teacher relationship quality
28 : Peer relationship quality
29 : Extra-curricular activities
30 : Section
31 : Household income level (standardized)
32 : Travel time to school (minutes)
33 : grade_number
34 : stream_letter
35 : subgroup
36 : level_prefix
37 : long_commute_flag
38 : long_walk_flag
39 : academic_domain
40 : attendance_domain
41 : socioeconomic_domain
42 : 

In [ ]:
import torch

PYG_URL = 'https://data.pyg.org/whl/torch-2.11+cpu.html' # Using the PYG_URL from the kernel state
!pip install torch_geometric -f {PYG_URL}

import pandas as pd
import numpy as np

from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split

from torch_geometric.data import Data
from torch_geometric.utils import to_undirected

Looking in links: https://data.pyg.org/whl/torch-2.11+cpu.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 25.9 MB/s eta 0:00:00


In [ ]:
import torch

graph_path = "/content/drive/MyDrive/real graph (1).pt"

graph = torch.load(graph_path, map_location="cpu", weights_only=False)

print("Graph type:", type(graph))

if hasattr(graph, "x"):
    print("Node features (x):", graph.x.shape)

if hasattr(graph, "edge_index"):
    print("Edge index:", graph.edge_index.shape)

if hasattr(graph, "y"):
    print("Labels (y):", graph.y.shape)
    print("Unique labels:", torch.unique(graph.y, return_counts=True))

print("\nGraph contents:")
print(graph)

Graph type: <class 'torch_geometric.data.data.Data'>
Node features (x): torch.Size([1000, 152])
Edge index: torch.Size([2, 8054])
Labels (y): torch.Size([1000])
Unique labels: (tensor([0, 1, 2]), tensor([250, 500, 250]))

Graph contents:
Data(x=[1000, 152], edge_index=[2, 8054], y=[1000], edge_weight=[8054], train_mask=[1000], val_mask=[1000], test_mask=[1000])


In [ ]:
print("Has train_mask:", hasattr(graph, "train_mask"))
print("Has val_mask:", hasattr(graph, "val_mask"))
print("Has test_mask:", hasattr(graph, "test_mask"))

if hasattr(graph, "train_mask"):
    print("Train:", graph.train_mask.sum().item())

if hasattr(graph, "val_mask"):
    print("Validation:", graph.val_mask.sum().item())

if hasattr(graph, "test_mask"):
    print("Test:", graph.test_mask.sum().item())

Has train_mask: True
Has val_mask: True
Has test_mask: True
Train: 700
Validation: 150
Test: 150


In [ ]:
train_mask = graph.train_mask
val_mask = graph.val_mask
test_mask = graph.test_mask

print("Train ∩ Validation:",
      (train_mask & val_mask).sum().item())

print("Train ∩ Test:",
      (train_mask & test_mask).sum().item())

print("Validation ∩ Test:",
      (val_mask & test_mask).sum().item())

print("Total assigned nodes:",
      (train_mask | val_mask | test_mask).sum().item())

Train ∩ Validation: 0
Train ∩ Test: 0
Validation ∩ Test: 0
Total assigned nodes: 1000


In [ ]:
import numpy as np
import torch

# ============================================================
# EXTRACT DATA FROM THE GRAPH
# ============================================================

X = graph.x.cpu().numpy()
y = graph.y.cpu().numpy()

train_mask = graph.train_mask.cpu().numpy().astype(bool)
val_mask = graph.val_mask.cpu().numpy().astype(bool)
test_mask = graph.test_mask.cpu().numpy().astype(bool)

# ------------------------------------------------------------
# Split features and labels
# ------------------------------------------------------------

X_train = X[train_mask]
y_train = y[train_mask]

X_val = X[val_mask]
y_val = y[val_mask]

X_test = X[test_mask]
y_test = y[test_mask]

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_val:", X_val.shape)
print("y_val:", y_val.shape)

print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

# ------------------------------------------------------------
# Class distributions
# ------------------------------------------------------------

print("\nTraining class distribution:")
print(np.bincount(y_train))

print("\nValidation class distribution:")
print(np.bincount(y_val))

print("\nTest class distribution:")
print(np.bincount(y_test))

X_train: (700, 152)
y_train: (700,)
X_val: (150, 152)
y_val: (150,)
X_test: (150, 152)
y_test: (150,)

Training class distribution:
[175 350 175]

Validation class distribution:
[37 75 38]

Test class distribution:
[38 75 37]


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

print("Scaled training data:", X_train_scaled.shape)
print("Scaled validation data:", X_val_scaled.shape)
print("Scaled test data:", X_test_scaled.shape)

Scaled training data: (700, 152)
Scaled validation data: (150, 152)
Scaled test data: (150, 152)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# LOGISTIC REGRESSION BASELINE
# ============================================================

logistic_model = LogisticRegression(
    max_iter=2000,
    random_state=42
)

logistic_model.fit(X_train_scaled, y_train)

# Predictions
y_val_pred = logistic_model.predict(X_val_scaled)
y_test_pred = logistic_model.predict(X_test_scaled)

# ------------------------------------------------------------
# Validation performance
# ------------------------------------------------------------

val_accuracy = accuracy_score(y_val, y_val_pred)
val_macro_f1 = f1_score(y_val, y_val_pred, average="macro")

print("LOGISTIC REGRESSION")
print("=" * 50)

print(f"Validation Accuracy: {val_accuracy:.4f}")
print(f"Validation Macro-F1: {val_macro_f1:.4f}")

# ------------------------------------------------------------
# Test performance
# ------------------------------------------------------------

test_accuracy = accuracy_score(y_test, y_test_pred)
test_macro_f1 = f1_score(y_test, y_test_pred, average="macro")

print(f"\nTest Accuracy: {test_accuracy:.4f}")
print(f"Test Macro-F1: {test_macro_f1:.4f}")

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_test_pred,
    target_names=["Low", "Medium", "High"]
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred))

LOGISTIC REGRESSION
Validation Accuracy: 0.8533
Validation Macro-F1: 0.8519

Test Accuracy: 0.8400
Test Macro-F1: 0.8402

Classification Report:
              precision    recall  f1-score   support

         Low       0.77      0.87      0.81        38
      Medium       0.82      0.87      0.84        75
        High       1.00      0.76      0.86        37

    accuracy                           0.84       150
   macro avg       0.86      0.83      0.84       150
weighted avg       0.85      0.84      0.84       150


Confusion Matrix:
[[33  5  0]
 [10 65  0]
 [ 0  9 28]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# RANDOM FOREST BASELINE
# ============================================================

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

# Train
rf_model.fit(X_train, y_train)

# Predictions
y_val_pred_rf = rf_model.predict(X_val)
y_test_pred_rf = rf_model.predict(X_test)

# ============================================================
# VALIDATION RESULTS
# ============================================================

val_accuracy_rf = accuracy_score(y_val, y_val_pred_rf)
val_macro_f1_rf = f1_score(
    y_val,
    y_val_pred_rf,
    average="macro"
)

print("RANDOM FOREST")
print("=" * 50)

print(f"Validation Accuracy: {val_accuracy_rf:.4f}")
print(f"Validation Macro-F1: {val_macro_f1_rf:.4f}")

# ============================================================
# TEST RESULTS
# ============================================================

test_accuracy_rf = accuracy_score(y_test, y_test_pred_rf)
test_macro_f1_rf = f1_score(
    y_test,
    y_test_pred_rf,
    average="macro"
)

print(f"\nTest Accuracy: {test_accuracy_rf:.4f}")
print(f"Test Macro-F1: {test_macro_f1_rf:.4f}")

# ============================================================
# CLASSIFICATION REPORT
# ============================================================

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_test_pred_rf,
        target_names=["Low", "Medium", "High"]
    )
)

# ============================================================
# CONFUSION MATRIX
# ============================================================

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_rf))

RANDOM FOREST
Validation Accuracy: 0.8400
Validation Macro-F1: 0.8295

Test Accuracy: 0.7800
Test Macro-F1: 0.7630

Classification Report:
              precision    recall  f1-score   support

         Low       0.91      0.76      0.83        38
      Medium       0.72      0.91      0.80        75
        High       0.83      0.54      0.66        37

    accuracy                           0.78       150
   macro avg       0.82      0.74      0.76       150
weighted avg       0.80      0.78      0.77       150


Confusion Matrix:
[[29  9  0]
 [ 3 68  4]
 [ 0 17 20]]


In [ ]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
import numpy as np
import pandas as pd

# ============================================================
# REPEATED STRATIFIED CROSS-VALIDATION
# ============================================================

N_SPLITS = 5
N_REPEATS = 10
SEED = 42

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=SEED
)

# Use ONLY the 700 training nodes
X_cv = X_train
y_cv = y_train

# ============================================================
# DEFINE MODELS
# ============================================================

models = {

    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(
            max_iter=2000,
            random_state=SEED
        ))
    ]),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        class_weight="balanced",
        random_state=SEED,
        n_jobs=-1
    )
}

# ============================================================
# STORAGE
# ============================================================

results = []

# ============================================================
# CROSS-VALIDATION
# ============================================================

for model_name, model in models.items():

    fold_accuracies = []
    fold_macro_f1 = []

    for train_idx, val_idx in cv.split(X_cv, y_cv):

        X_fold_train = X_cv[train_idx]
        X_fold_val = X_cv[val_idx]

        y_fold_train = y_cv[train_idx]
        y_fold_val = y_cv[val_idx]

        # Train
        model.fit(X_fold_train, y_fold_train)

        # Predict
        y_pred = model.predict(X_fold_val)

        # Metrics
        accuracy = accuracy_score(
            y_fold_val,
            y_pred
        )

        macro_f1 = f1_score(
            y_fold_val,
            y_pred,
            average="macro"
        )

        fold_accuracies.append(accuracy)
        fold_macro_f1.append(macro_f1)

    # Store results
    results.append({
        "Model": model_name,

        "Accuracy Mean": np.mean(fold_accuracies),
        "Accuracy Std": np.std(fold_accuracies),

        "Macro-F1 Mean": np.mean(fold_macro_f1),
        "Macro-F1 Std": np.std(fold_macro_f1)
    })

# ============================================================
# RESULTS TABLE
# ============================================================

baseline_cv_results = pd.DataFrame(results)

print("\nREPEATED CROSS-VALIDATION RESULTS")
print("=" * 70)

print(
    baseline_cv_results.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


REPEATED CROSS-VALIDATION RESULTS
              Model  Accuracy Mean  Accuracy Std  Macro-F1 Mean  Macro-F1 Std
Logistic Regression         0.8340        0.0272         0.8324        0.0272
      Random Forest         0.7986        0.0310         0.7827        0.0369


In [ ]:
# ============================================================
# FINAL BASELINE EVALUATION ON UNTOUCHED TEST SET
# ============================================================

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix
)

SEED = 42

# ============================================================
# FINAL MODELS
# ============================================================

final_models = {

    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(
            max_iter=2000,
            random_state=SEED
        ))
    ]),

    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        class_weight="balanced",
        random_state=SEED,
        n_jobs=-1
    )
}

final_results = []

# ============================================================
# TRAIN ON ALL 700 TRAINING NODES
# ============================================================

for model_name, model in final_models.items():

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)

    macro_f1 = f1_score(
        y_test,
        y_pred,
        average="macro"
    )

    macro_precision = precision_score(
        y_test,
        y_pred,
        average="macro"
    )

    macro_recall = recall_score(
        y_test,
        y_pred,
        average="macro"
    )

    final_results.append({
        "Model": model_name,
        "Test Accuracy": accuracy,
        "Test Macro-F1": macro_f1,
        "Test Macro-Precision": macro_precision,
        "Test Macro-Recall": macro_recall
    })

    print("\n" + "=" * 70)
    print(model_name)
    print("=" * 70)

    print(f"Test Accuracy:        {accuracy:.4f}")
    print(f"Test Macro-F1:        {macro_f1:.4f}")
    print(f"Test Macro-Precision: {macro_precision:.4f}")
    print(f"Test Macro-Recall:    {macro_recall:.4f}")

    print("\nClassification Report:")
    print(
        classification_report(
            y_test,
            y_pred,
            target_names=["Low", "Medium", "High"]
        )
    )

    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))


# ============================================================
# FINAL RESULTS TABLE
# ============================================================

final_baseline_results = pd.DataFrame(final_results)

print("\n\nFINAL BASELINE RESULTS")
print("=" * 70)

print(
    final_baseline_results.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)


Logistic Regression
Test Accuracy:        0.8400
Test Macro-F1:        0.8402
Test Macro-Precision: 0.8634
Test Macro-Recall:    0.8306

Classification Report:
              precision    recall  f1-score   support

         Low       0.77      0.87      0.81        38
      Medium       0.82      0.87      0.84        75
        High       1.00      0.76      0.86        37

    accuracy                           0.84       150
   macro avg       0.86      0.83      0.84       150
weighted avg       0.85      0.84      0.84       150

Confusion Matrix:
[[33  5  0]
 [10 65  0]
 [ 0  9 28]]

Random Forest
Test Accuracy:        0.7800
Test Macro-F1:        0.7630
Test Macro-Precision: 0.8210
Test Macro-Recall:    0.7368

Classification Report:
              precision    recall  f1-score   support

         Low       0.91      0.76      0.83        38
      Medium       0.72      0.91      0.80        75
        High       0.83      0.54      0.66        37

    accuracy                  

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import SAGEConv

# ============================================================
# PLAIN GRAPHSAGE - MEAN AGGREGATION
# ============================================================

class GraphSAGE(nn.Module):

    def __init__(
        self,
        in_channels,
        hidden_channels=64,
        out_channels=3,
        dropout=0.5
    ):
        super().__init__()

        self.conv1 = SAGEConv(
            in_channels,
            hidden_channels,
            aggr="mean"
        )

        self.conv2 = SAGEConv(
            hidden_channels,
            out_channels,
            aggr="mean"
        )

        self.dropout = dropout

    def forward(self, x, edge_index):

        x = self.conv1(x, edge_index)

        x = F.relu(x)

        x = F.dropout(
            x,
            p=self.dropout,
            training=self.training
        )

        x = self.conv2(x, edge_index)

        return x

In [ ]:


device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

graph = graph.to(device)

print("Device:", device)
print("Nodes:", graph.x.shape[0])
print("Features:", graph.x.shape[1])
print("Edges:", graph.edge_index.shape[1])

print("Train nodes:", graph.train_mask.sum().item())
print("Validation nodes:", graph.val_mask.sum().item())
print("Test nodes:", graph.test_mask.sum().item())

Device: cpu
Nodes: 1000
Features: 152
Edges: 8054
Train nodes: 700
Validation nodes: 150
Test nodes: 150


In [ ]:
from sklearn.metrics import accuracy_score, f1_score

# ============================================================
# GRAPHSAGE TRAINING
# ============================================================

SEED = 42

torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

model = GraphSAGE(
    in_channels=graph.x.shape[1],
    hidden_channels=64,
    out_channels=3,
    dropout=0.5
).to(device)

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.001,
    weight_decay=5e-4
)

criterion = nn.CrossEntropyLoss()

# Early stopping settings
MAX_EPOCHS = 200
PATIENCE = 30

best_val_f1 = -float("inf")
best_state = None
patience_counter = 0

# ============================================================
# TRAINING LOOP
# ============================================================

for epoch in range(1, MAX_EPOCHS + 1):

    # --------------------------------------------------------
    # TRAIN
    # --------------------------------------------------------

    model.train()

    optimizer.zero_grad()

    out = model(
        graph.x,
        graph.edge_index
    )

    loss = criterion(
        out[graph.train_mask],
        graph.y[graph.train_mask]
    )

    loss.backward()

    optimizer.step()

    # --------------------------------------------------------
    # VALIDATION
    # --------------------------------------------------------

    model.eval()

    with torch.no_grad():

        val_out = model(
            graph.x,
            graph.edge_index
        )

        val_pred = val_out[
            graph.val_mask
        ].argmax(dim=1)

        val_true = graph.y[
            graph.val_mask
        ]

        val_accuracy = accuracy_score(
            val_true.cpu().numpy(),
            val_pred.cpu().numpy()
        )

        val_macro_f1 = f1_score(
            val_true.cpu().numpy(),
            val_pred.cpu().numpy(),
            average="macro"
        )

    # --------------------------------------------------------
    # EARLY STOPPING
    # --------------------------------------------------------

    if val_macro_f1 > best_val_f1:

        best_val_f1 = val_macro_f1

        best_state = {
            key: value.detach().cpu().clone()
            for key, value in model.state_dict().items()
        }

        patience_counter = 0

    else:

        patience_counter += 1



    if epoch == 1 or epoch % 10 == 0:

        print(
            f"Epoch {epoch:03d} | "
            f"Loss: {loss.item():.4f} | "
            f"Val Acc: {val_accuracy:.4f} | "
            f"Val Macro-F1: {val_macro_f1:.4f}"
        )

    if patience_counter >= PATIENCE:

        print(
            f"\nEarly stopping at epoch {epoch}"
        )

        break

Epoch 001 | Loss: 1.1067 | Val Acc: 0.4333 | Val Macro-F1: 0.3147
Epoch 010 | Loss: 0.9334 | Val Acc: 0.5000 | Val Macro-F1: 0.2222
Epoch 020 | Loss: 0.8014 | Val Acc: 0.5867 | Val Macro-F1: 0.4110
Epoch 030 | Loss: 0.6550 | Val Acc: 0.7667 | Val Macro-F1: 0.7585
Epoch 040 | Loss: 0.5314 | Val Acc: 0.7667 | Val Macro-F1: 0.7578
Epoch 050 | Loss: 0.4430 | Val Acc: 0.7733 | Val Macro-F1: 0.7715
Epoch 060 | Loss: 0.3837 | Val Acc: 0.7867 | Val Macro-F1: 0.7865
Epoch 070 | Loss: 0.3533 | Val Acc: 0.8200 | Val Macro-F1: 0.8158
Epoch 080 | Loss: 0.3061 | Val Acc: 0.8333 | Val Macro-F1: 0.8303
Epoch 090 | Loss: 0.2739 | Val Acc: 0.8533 | Val Macro-F1: 0.8518
Epoch 100 | Loss: 0.2534 | Val Acc: 0.8733 | Val Macro-F1: 0.8718
Epoch 110 | Loss: 0.2345 | Val Acc: 0.8733 | Val Macro-F1: 0.8722
Epoch 120 | Loss: 0.2204 | Val Acc: 0.8600 | Val Macro-F1: 0.8585
Epoch 130 | Loss: 0.1865 | Val Acc: 0.8600 | Val Macro-F1: 0.8580
Epoch 140 | Loss: 0.1756 | Val Acc: 0.8533 | Val Macro-F1: 0.8511

Early sto

In [ ]:

model.load_state_dict(best_state)

print(
    f"Best Validation Macro-F1: "
    f"{best_val_f1:.4f}"
)

Best Validation Macro-F1: 0.8788


In [ ]:
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# FINAL TEST EVALUATION
# ============================================================

model.eval()

with torch.no_grad():

    out = model(
        graph.x,
        graph.edge_index
    )

    test_pred = out[
        graph.test_mask
    ].argmax(dim=1)

    test_true = graph.y[
        graph.test_mask
    ]

# Convert to NumPy
test_true_np = test_true.cpu().numpy()
test_pred_np = test_pred.cpu().numpy()

# Metrics
test_accuracy = accuracy_score(
    test_true_np,
    test_pred_np
)

test_macro_f1 = f1_score(
    test_true_np,
    test_pred_np,
    average="macro"
)

test_macro_precision = precision_score(
    test_true_np,
    test_pred_np,
    average="macro"
)

test_macro_recall = recall_score(
    test_true_np,
    test_pred_np,
    average="macro"
)

print("=" * 70)
print("PLAIN GRAPHSAGE - MEAN AGGREGATION")
print("=" * 70)

print(f"Test Accuracy:        {test_accuracy:.4f}")
print(f"Test Macro-F1:        {test_macro_f1:.4f}")
print(f"Test Macro-Precision: {test_macro_precision:.4f}")
print(f"Test Macro-Recall:    {test_macro_recall:.4f}")

print("\nClassification Report:")

print(
    classification_report(
        test_true_np,
        test_pred_np,
        target_names=[
            "Low",
            "Medium",
            "High"
        ]
    )
)

print("Confusion Matrix:")

print(
    confusion_matrix(
        test_true_np,
        test_pred_np
    )
)

PLAIN GRAPHSAGE - MEAN AGGREGATION
Test Accuracy:        0.8200
Test Macro-F1:        0.8187
Test Macro-Precision: 0.8214
Test Macro-Recall:    0.8173

Classification Report:
              precision    recall  f1-score   support

         Low       0.82      0.87      0.85        38
      Medium       0.82      0.83      0.82        75
        High       0.82      0.76      0.79        37

    accuracy                           0.82       150
   macro avg       0.82      0.82      0.82       150
weighted avg       0.82      0.82      0.82       150

Confusion Matrix:
[[33  5  0]
 [ 7 62  6]
 [ 0  9 28]]


In [ ]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.metrics import accuracy_score, f1_score
from lightgbm import LGBMClassifier

import numpy as np

N_SPLITS = 5
N_REPEATS = 10
SEED = 42

cv = RepeatedStratifiedKFold(
    n_splits=N_SPLITS,
    n_repeats=N_REPEATS,
    random_state=SEED
)

X_cv = X_train
y_cv = y_train

lgbm_model = LGBMClassifier(
    objective="multiclass",
    num_class=3,
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=31,
    max_depth=-1,
    class_weight="balanced",
    random_state=SEED,
    verbosity=-1,
    n_jobs=-1
)

fold_accuracies = []
fold_macro_f1 = []

for train_idx, val_idx in cv.split(X_cv, y_cv):

    X_fold_train = X_cv[train_idx]
    X_fold_val = X_cv[val_idx]

    y_fold_train = y_cv[train_idx]
    y_fold_val = y_cv[val_idx]

    lgbm_model.fit(
        X_fold_train,
        y_fold_train
    )

    y_pred = lgbm_model.predict(
        X_fold_val
    )

    fold_accuracies.append(
        accuracy_score(
            y_fold_val,
            y_pred
        )
    )

    fold_macro_f1.append(
        f1_score(
            y_fold_val,
            y_pred,
            average="macro"
        )
    )

print("LIGHTGBM")
print("=" * 50)

print(
    f"Accuracy: "
    f"{np.mean(fold_accuracies):.4f} "
    f"± {np.std(fold_accuracies):.4f}"
)

print(
    f"Macro-F1: "
    f"{np.mean(fold_macro_f1):.4f} "
    f"± {np.std(fold_macro_f1):.4f}"
)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/ut

LIGHTGBM
Accuracy: 0.8406 ± 0.0284
Macro-F1: 0.8389 ± 0.0295


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


In [ ]:
from lightgbm import LGBMClassifier
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix
)

# ============================================================
# FINAL LIGHTGBM MODEL
# ============================================================

SEED = 42

final_lgbm = LGBMClassifier(
    objective="multiclass",
    num_class=3,
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=31,
    max_depth=-1,
    class_weight="balanced",
    random_state=SEED,
    verbosity=-1,
    n_jobs=-1
)

# Train ONLY on the 700 training nodes
final_lgbm.fit(
    X_train,
    y_train
)

# Predict on the untouched 150-node test set
y_test_pred_lgbm = final_lgbm.predict(
    X_test
)

# ============================================================
# METRICS
# ============================================================

test_accuracy_lgbm = accuracy_score(
    y_test,
    y_test_pred_lgbm
)

test_macro_f1_lgbm = f1_score(
    y_test,
    y_test_pred_lgbm,
    average="macro"
)

test_macro_precision_lgbm = precision_score(
    y_test,
    y_test_pred_lgbm,
    average="macro"
)

test_macro_recall_lgbm = recall_score(
    y_test,
    y_test_pred_lgbm,
    average="macro"
)

print("=" * 70)
print("FINAL LIGHTGBM TEST RESULTS")
print("=" * 70)

print(f"Test Accuracy:        {test_accuracy_lgbm:.4f}")
print(f"Test Macro-F1:        {test_macro_f1_lgbm:.4f}")
print(f"Test Macro-Precision: {test_macro_precision_lgbm:.4f}")
print(f"Test Macro-Recall:    {test_macro_recall_lgbm:.4f}")

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_test_pred_lgbm,
        target_names=[
            "Low",
            "Medium",
            "High"
        ]
    )
)

print("Confusion Matrix:")

print(
    confusion_matrix(
        y_test,
        y_test_pred_lgbm
    )
)

FINAL LIGHTGBM TEST RESULTS
Test Accuracy:        0.8133
Test Macro-F1:        0.8143
Test Macro-Precision: 0.8108
Test Macro-Recall:    0.8217

Classification Report:
              precision    recall  f1-score   support

         Low       0.77      0.89      0.83        38
      Medium       0.83      0.79      0.81        75
        High       0.83      0.78      0.81        37

    accuracy                           0.81       150
   macro avg       0.81      0.82      0.81       150
weighted avg       0.82      0.81      0.81       150

Confusion Matrix:
[[34  4  0]
 [10 59  6]
 [ 0  8 29]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


In [ ]:
import torch

PYG_URL = 'https://data.pyg.org/whl/torch-2.11+cpu.html'
!pip install torch_geometric -f {PYG_URL}

from torch_geometric.data import Data

data = torch.load(
    "/content/drive/MyDrive/Synthetic_school_data_full.pt",
    weights_only=False
)

print(data)
print("\nNode features:", data.x.shape)
print("Edges:", data.edge_index.shape)
print("Labels:", data.y.shape)

print("\nUnique labels and counts:")
print(torch.unique(data.y, return_counts=True))

print("\nTrain nodes:", data.train_mask.sum().item())
print("Validation nodes:", data.val_mask.sum().item())
print("Test nodes:", data.test_mask.sum().item())

Looking in links: https://data.pyg.org/whl/torch-2.11+cpu.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 69.0 MB/s eta 0:00:00
Data(x=[3000, 34], edge_index=[2, 18708], edge_attr=[18708], y=[3000], train_mask=[3000], val_mask=[3000], test_mask=[3000])

Node features: torch.Size([3000, 34])
Edges: torch.Size([2, 18708])
Labels: torch.Size([3000])

Unique labels and counts:
(tensor([0, 1, 2]), tensor([ 810, 1349,  841]))

Train nodes: 2100
Validation nodes: 450
Test nodes: 450


**SYNTHETIC DATASET BASELINE MODELS**

In [2]:
import torch

PYG_URL = 'https://data.pyg.org/whl/torch-2.11+cpu.html'
!pip install torch_geometric -f {PYG_URL}

from torch_geometric.data import Data

synthetic_data = torch.load(
    "/content/drive/MyDrive/Synthetic_school_data_full.pt",
    weights_only=False
)

Looking in links: https://data.pyg.org/whl/torch-2.11+cpu.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 12.8 MB/s eta 0:00:00
ERROR: Operation cancelled by user


ModuleNotFoundError: No module named 'torch_geometric'

In [ ]:
print(synthetic_data)

Data(x=[3000, 34], edge_index=[2, 18708], edge_attr=[18708], y=[3000], train_mask=[3000], val_mask=[3000], test_mask=[3000])


In [ ]:
X_syn = synthetic_data.x.cpu().numpy()
y_syn = synthetic_data.y.cpu().numpy()

train_mask_syn = synthetic_data.train_mask.cpu().numpy()
val_mask_syn = synthetic_data.val_mask.cpu().numpy()
test_mask_syn = synthetic_data.test_mask.cpu().numpy()

In [ ]:
# ============================================================
# SYNTHETIC DATA — LOGISTIC REGRESSION
# ============================================================

import torch
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix
)

# ------------------------------------------------------------
# 1. LOAD SYNTHETIC GRAPH
# ------------------------------------------------------------

synthetic_data = torch.load(
    "/content/drive/MyDrive/Synthetic_school_data_full.pt",
    weights_only=False
)

print("Synthetic Graph:")
print(synthetic_data)

# ------------------------------------------------------------
# 2. EXTRACT FEATURES, LABELS AND MASKS
# ------------------------------------------------------------

X_syn = synthetic_data.x.cpu().numpy()
y_syn = synthetic_data.y.cpu().numpy()

train_mask_syn = synthetic_data.train_mask.cpu().numpy()
val_mask_syn = synthetic_data.val_mask.cpu().numpy()
test_mask_syn = synthetic_data.test_mask.cpu().numpy()

# Convert masks to indices
train_idx_syn = np.where(train_mask_syn)[0]
val_idx_syn = np.where(val_mask_syn)[0]
test_idx_syn = np.where(test_mask_syn)[0]

# ------------------------------------------------------------
# 3. CREATE TRAIN / VALIDATION / TEST SETS
# ------------------------------------------------------------

X_train_syn = X_syn[train_idx_syn]
y_train_syn = y_syn[train_idx_syn]

X_val_syn = X_syn[val_idx_syn]
y_val_syn = y_syn[val_idx_syn]

X_test_syn = X_syn[test_idx_syn]
y_test_syn = y_syn[test_idx_syn]

print("\nDataset split:")
print("Training:", X_train_syn.shape, y_train_syn.shape)
print("Validation:", X_val_syn.shape, y_val_syn.shape)
print("Test:", X_test_syn.shape, y_test_syn.shape)

# ------------------------------------------------------------
# 4. TRAIN LOGISTIC REGRESSION
# ------------------------------------------------------------

lr_syn = LogisticRegression(
    max_iter=2000,
    random_state=42
)

lr_syn.fit(X_train_syn, y_train_syn)

# ------------------------------------------------------------
# 5. VALIDATION EVALUATION
# ------------------------------------------------------------

y_val_pred_syn = lr_syn.predict(X_val_syn)

val_accuracy_syn = accuracy_score(y_val_syn, y_val_pred_syn)
val_macro_f1_syn = f1_score(
    y_val_syn,
    y_val_pred_syn,
    average="macro"
)

print("\n" + "=" * 60)
print("SYNTHETIC DATA — LOGISTIC REGRESSION")
print("=" * 60)

print(f"\nValidation Accuracy: {val_accuracy_syn:.4f}")
print(f"Validation Macro-F1: {val_macro_f1_syn:.4f}")

# ------------------------------------------------------------
# 6. TEST EVALUATION
# ------------------------------------------------------------

y_test_pred_syn = lr_syn.predict(X_test_syn)

test_accuracy_syn = accuracy_score(
    y_test_syn,
    y_test_pred_syn
)

test_macro_f1_syn = f1_score(
    y_test_syn,
    y_test_pred_syn,
    average="macro"
)

test_macro_precision_syn = precision_score(
    y_test_syn,
    y_test_pred_syn,
    average="macro",
    zero_division=0
)

test_macro_recall_syn = recall_score(
    y_test_syn,
    y_test_pred_syn,
    average="macro",
    zero_division=0
)

# ------------------------------------------------------------
# 7. FINAL TEST RESULTS
# ------------------------------------------------------------

print("\nTest Accuracy:        {:.4f}".format(test_accuracy_syn))
print("Test Macro-F1:        {:.4f}".format(test_macro_f1_syn))
print("Test Macro-Precision: {:.4f}".format(test_macro_precision_syn))
print("Test Macro-Recall:    {:.4f}".format(test_macro_recall_syn))

# ------------------------------------------------------------
# 8. CLASSIFICATION REPORT
# ------------------------------------------------------------

print("\nClassification Report:")

print(
    classification_report(
        y_test_syn,
        y_test_pred_syn,
        target_names=["Low", "Medium", "High"],
        digits=2,
        zero_division=0
    )
)

# ------------------------------------------------------------
# 9. CONFUSION MATRIX
# ------------------------------------------------------------

cm_syn = confusion_matrix(
    y_test_syn,
    y_test_pred_syn
)

print("Confusion Matrix:")
print(cm_syn)

Synthetic Graph:
Data(x=[3000, 34], edge_index=[2, 18708], edge_attr=[18708], y=[3000], train_mask=[3000], val_mask=[3000], test_mask=[3000])

Dataset split:
Training: (2100, 34) (2100,)
Validation: (450, 34) (450,)
Test: (450, 34) (450,)

SYNTHETIC DATA — LOGISTIC REGRESSION

Validation Accuracy: 0.4467
Validation Macro-F1: 0.2574

Test Accuracy:        0.4444
Test Macro-F1:        0.2568
Test Macro-Precision: 0.3537
Test Macro-Recall:    0.3402

Classification Report:
              precision    recall  f1-score   support

         Low       0.41      0.06      0.10       121
      Medium       0.46      0.93      0.61       203
        High       0.19      0.03      0.05       126

    accuracy                           0.44       450
   macro avg       0.35      0.34      0.26       450
weighted avg       0.37      0.44      0.32       450

Confusion Matrix:
[[  7 109   5]
 [  2 189  12]
 [  8 114   4]]


In [ ]:
# ============================================================
# SYNTHETIC FEATURE DIAGNOSTICS
# ============================================================

print("Number of features:", X_syn.shape[1])

print("\nFeature names:")
for i, feature in enumerate(synthetic_data.feature_names if hasattr(synthetic_data, "feature_names") else []):
    print(i, feature)

Number of features: 34

Feature names:


In [ ]:
print("\nFeature standard deviations:")

feature_std = X_train_syn.std(axis=0)

print(feature_std)

print("\nNumber of zero-variance features:",
      np.sum(feature_std == 0))


Feature standard deviations:
[0.99449426 0.68405724 1.0176864  1.9138185  0.09468826 0.06532477
 0.48920825 0.7831549  0.88120526 0.7746536  0.8006105  0.3853727
 0.4997357  0.4719033  0.49868998 0.41132075 0.4319094  0.3752138
 0.4957256  0.48900408 0.40142575 0.4994745  0.10629099 0.21092226
 0.40662935 0.4544208  0.30189264 0.3012676  0.28481364 0.35707474
 0.49898404 0.48585278 0.10994034 0.05604118]

Number of zero-variance features: 0


In [ ]:
unique_pred, pred_counts = np.unique(
    y_test_pred_syn,
    return_counts=True
)

print("\nPredicted class distribution:")

for cls, count in zip(unique_pred, pred_counts):
    print(
        f"Class {cls}: {count} "
        f"({count / len(y_test_pred_syn):.2%})"
    )


Predicted class distribution:
Class 0: 17 (3.78%)
Class 1: 412 (91.56%)
Class 2: 21 (4.67%)


In [ ]:
# ============================================================
# SYNTHETIC DATA — FEATURE/TARGET DIAGNOSTIC
# ============================================================

# Correlation between each feature and the target
correlations = []

for i in range(X_syn.shape[1]):
    corr = np.corrcoef(X_syn[:, i], y_syn)[0, 1]
    correlations.append(corr)

correlations = np.array(correlations)

print("Absolute feature-target correlations:")
print(np.sort(np.abs(correlations))[::-1])

print("\nStrongest correlations:")
for idx in np.argsort(np.abs(correlations))[::-1][:10]:
    print(
        f"Feature {idx}: "
        f"correlation = {correlations[idx]:.4f}"
    )

Absolute feature-target correlations:
[0.04982894 0.04736958 0.03829167 0.0372681  0.0307358  0.02634999
 0.02514048 0.02476115 0.02464312 0.02094456 0.0207965  0.02041365
 0.01909995 0.01454817 0.01441787 0.01423154 0.01276362 0.01231556
 0.01228191 0.01190851 0.01154018 0.00962138 0.0091217  0.00854799
 0.00847121 0.0076352  0.00716027 0.0064667  0.00560473 0.00508309
 0.0043693  0.00206111 0.00102936 0.00025551]

Strongest correlations:
Feature 14: correlation = -0.0498
Feature 1: correlation = 0.0474
Feature 15: correlation = 0.0383
Feature 0: correlation = 0.0373
Feature 28: correlation = 0.0307
Feature 11: correlation = -0.0263
Feature 8: correlation = -0.0251
Feature 31: correlation = -0.0248
Feature 33: correlation = -0.0246
Feature 30: correlation = 0.0209


In [ ]:
# ============================================================
# CLASS-WISE FEATURE MEANS
# ============================================================

for cls, name in zip([0, 1, 2], ["Low", "Medium", "High"]):

    class_mean = X_syn[y_syn == cls].mean(axis=0)

    print(f"\n{name} — first 10 feature means:")
    print(np.round(class_mean[:10], 4))


Low — first 10 feature means:
[-5.9600e-02  2.2432e+00  1.4500e-02  4.3778e+00  4.9000e-03  3.7000e-03
  4.1730e-01  1.2383e+00  9.4070e-01  1.3741e+00]

Medium — first 10 feature means:
[ 1.0100e-02  2.2595e+00 -1.4000e-02  4.4314e+00  8.9000e-03  3.7000e-03
  3.9440e-01  1.2609e+00  9.1480e-01  1.3877e+00]

High — first 10 feature means:
[0.0412 2.3306 0.0085 4.4828 0.0083 0.0059 0.4043 1.2521 0.8811 1.3722]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report

# Convert tensors to NumPy
X_np = X.cpu().numpy()
y_np = y.cpu().numpy()

# Get the same splits used by the GAT
train_idx = train_mask.cpu().numpy()
val_idx = val_mask.cpu().numpy()
test_idx = test_mask.cpu().numpy()

# Create Random Forest
rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

# Train
rf.fit(X_np[train_idx], y_np[train_idx])

# Predictions
train_pred = rf.predict(X_np[train_idx])
val_pred = rf.predict(X_np[val_idx])
test_pred = rf.predict(X_np[test_idx])

# Evaluation
train_acc = accuracy_score(y_np[train_idx], train_pred)
val_acc = accuracy_score(y_np[val_idx], val_pred)
test_acc = accuracy_score(y_np[test_idx], test_pred)

train_f1 = f1_score(y_np[train_idx], train_pred, average="macro")
val_f1 = f1_score(y_np[val_idx], val_pred, average="macro")
test_f1 = f1_score(y_np[test_idx], test_pred, average="macro")

print("Random Forest Results")
print("=" * 40)
print(f"Train Accuracy: {train_acc:.4f}")
print(f"Train Macro-F1: {train_f1:.4f}")
print(f"Validation Accuracy: {val_acc:.4f}")
print(f"Validation Macro-F1: {val_f1:.4f}")
print(f"Test Accuracy: {test_acc:.4f}")
print(f"Test Macro-F1: {test_f1:.4f}")

print("\nClassification Report:")
print(classification_report(
    y_np[test_idx],
    test_pred,
    target_names=["Low", "Medium", "High"]
))

NameError: name 'X' is not defined

In [ ]:
# Check your graph object
print(data)
print("Features:", data.x.shape)
print("Labels:", data.y.shape)
print("Classes:", torch.unique(data.y, return_counts=True))

NameError: name 'data' is not defined

In [ ]:
print("Variables containing 'data':")
print([v for v in dir() if 'data' in v.lower()])

print("\nVariables containing 'graph':")
print([v for v in dir() if 'graph' in v.lower()])

print("\nVariables containing 'mask':")
print([v for v in dir() if 'mask' in v.lower()])

print("\nVariables containing 'train':")
print([v for v in dir() if 'train' in v.lower()])

Variables containing 'data':
['Data', 'synthetic_data']

Variables containing 'graph':
[]

Variables containing 'mask':
['test_mask_syn', 'train_mask_syn', 'val_mask_syn']

Variables containing 'train':
['X_train_syn', 'train_idx_syn', 'train_mask_syn', 'y_train_syn']


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report

# Get synthetic features and labels
X_syn = synthetic_data.x.cpu().numpy()
y_syn = synthetic_data.y.cpu().numpy()

# Convert masks to NumPy (they are already numpy arrays, so just assign them)
train_idx = train_mask_syn
val_idx = val_mask_syn
test_idx = test_mask_syn

# Check the split sizes
print("Train:", train_idx.sum())
print("Validation:", val_idx.sum())
print("Test:", test_idx.sum())

# Create Random Forest
rf_syn = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

# Train
rf_syn.fit(
    X_syn[train_idx],
    y_syn[train_idx]
)

# Predictions
train_pred = rf_syn.predict(X_syn[train_idx])
val_pred = rf_syn.predict(X_syn[val_idx])
test_pred = rf_syn.predict(X_syn[test_idx])

# Calculate metrics
train_acc = accuracy_score(y_syn[train_idx], train_pred)
val_acc = accuracy_score(y_syn[val_idx], val_pred)
test_acc = accuracy_score(y_syn[test_idx], test_pred)

train_f1 = f1_score(y_syn[train_idx], train_pred, average="macro")
val_f1 = f1_score(y_syn[val_idx], val_pred, average="macro")
test_f1 = f1_score(y_syn[test_idx], test_pred, average="macro")

print("\n" + "=" * 50)
print("RANDOM FOREST — SYNTHETIC DATASET")
print("=" * 50)

print(f"Train Accuracy:       {train_acc:.4f}")
print(f"Train Macro-F1:       {train_f1:.4f}")
print(f"Validation Accuracy:  {val_acc:.4f}")
print(f"Validation Macro-F1:  {val_f1:.4f}")
print(f"Test Accuracy:        {test_acc:.4f}")
print(f"Test Macro-F1:        {test_f1:.4f}")

print("\nClassification Report — Test Set")
print("=" * 50)

print(classification_report(
    y_syn[test_idx],
    test_pred,
    target_names=["Low", "Medium", "High"]
))

AttributeError: 'numpy.ndarray' object has no attribute 'numpy'

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, classification_report

# Get synthetic features and labels
X_syn = synthetic_data.x.cpu().numpy()
y_syn = synthetic_data.y.cpu().numpy()

# Masks are ALREADY NumPy arrays
train_idx = train_mask_syn
val_idx = val_mask_syn
test_idx = test_mask_syn

# Check split sizes
print("Train:", train_idx.sum())
print("Validation:", val_idx.sum())
print("Test:", test_idx.sum())

# Create Random Forest
rf_syn = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

# Train
rf_syn.fit(
    X_syn[train_idx],
    y_syn[train_idx]
)

# Predictions
train_pred = rf_syn.predict(X_syn[train_idx])
val_pred = rf_syn.predict(X_syn[val_idx])
test_pred = rf_syn.predict(X_syn[test_idx])

# Metrics
train_acc = accuracy_score(y_syn[train_idx], train_pred)
val_acc = accuracy_score(y_syn[val_idx], val_pred)
test_acc = accuracy_score(y_syn[test_idx], test_pred)

train_f1 = f1_score(y_syn[train_idx], train_pred, average="macro")
val_f1 = f1_score(y_syn[val_idx], val_pred, average="macro")
test_f1 = f1_score(y_syn[test_idx], test_pred, average="macro")

print("\n" + "=" * 50)
print("RANDOM FOREST — SYNTHETIC DATASET")
print("=" * 50)

print(f"Train Accuracy:       {train_acc:.4f}")
print(f"Train Macro-F1:       {train_f1:.4f}")
print(f"Validation Accuracy:  {val_acc:.4f}")
print(f"Validation Macro-F1:  {val_f1:.4f}")
print(f"Test Accuracy:        {test_acc:.4f}")
print(f"Test Macro-F1:        {test_f1:.4f}")

print("\nClassification Report — Test Set")
print("=" * 50)

print(classification_report(
    y_syn[test_idx],
    test_pred,
    target_names=["Low", "Medium", "High"]
))

Train: 2100
Validation: 450
Test: 450

RANDOM FOREST — SYNTHETIC DATASET
Train Accuracy:       1.0000
Train Macro-F1:       1.0000
Validation Accuracy:  0.4311
Validation Macro-F1:  0.2968
Test Accuracy:        0.4356
Test Macro-F1:        0.2820

Classification Report — Test Set
              precision    recall  f1-score   support

         Low       0.30      0.09      0.14       121
      Medium       0.46      0.87      0.60       203
        High       0.27      0.06      0.10       126

    accuracy                           0.44       450
   macro avg       0.34      0.34      0.28       450
weighted avg       0.36      0.44      0.34       450



In [4]:
import torch
import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

PYG_URL = 'https://data.pyg.org/whl/torch-2.11+cpu.html'
!pip install torch_geometric -f {PYG_URL}
from torch_geometric.data import Data

# Load graph
data = torch.load(
    "/content/drive/MyDrive/Synthetic_student_graph.pt",
    weights_only=False
)

# Convert tensors to NumPy
X = data.x.numpy()
y = data.y.numpy()

train_mask = data.train_mask.numpy()
val_mask = data.val_mask.numpy()
test_mask = data.test_mask.numpy()

X_train = X[train_mask]
X_val   = X[val_mask]
X_test  = X[test_mask]

y_train = y[train_mask]
y_val   = y[val_mask]
y_test  = y[test_mask]

print("Train:", X_train.shape, y_train.shape)
print("Validation:", X_val.shape, y_val.shape)
print("Test:", X_test.shape, y_test.shape)

Looking in links: https://data.pyg.org/whl/torch-2.11+cpu.html
  Using cached torch_geometric-2.8.0.post1-py3-none-any.whl.metadata (64 kB)
Using cached torch_geometric-2.8.0.post1-py3-none-any.whl (1.3 MB)
Train: (2091, 174) (2091,)
Validation: (448, 174) (448,)
Test: (449, 174) (449,)


**LOGISTIC REGRESSION**

In [5]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=2000,
    random_state=42
)

lr.fit(X_train, y_train)

# Predictions
train_pred = lr.predict(X_train)
val_pred = lr.predict(X_val)
test_pred = lr.predict(X_test)


# Metrics
print("=" * 55)
print("LOGISTIC REGRESSION — SYNTHETIC DATASET")
print("=" * 55)

print(f"Train Accuracy:       {accuracy_score(y_train, train_pred):.4f}")
print(f"Train Macro-F1:       {f1_score(y_train, train_pred, average='macro'):.4f}")

print(f"Validation Accuracy:  {accuracy_score(y_val, val_pred):.4f}")
print(f"Validation Macro-F1:  {f1_score(y_val, val_pred, average='macro'):.4f}")

print(f"Test Accuracy:        {accuracy_score(y_test, test_pred):.4f}")
print(f"Test Macro-F1:        {f1_score(y_test, test_pred, average='macro'):.4f}")

print("\nClassification Report — Test")
print(classification_report(y_test, test_pred))

LOGISTIC REGRESSION — SYNTHETIC DATASET
Train Accuracy:       0.9971
Train Macro-F1:       0.9971
Validation Accuracy:  0.9821
Validation Macro-F1:  0.9820
Test Accuracy:        0.9800
Test Macro-F1:        0.9799

Classification Report — Test
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       112
           1       0.97      0.99      0.98       225
           2       0.97      0.99      0.98       112

    accuracy                           0.98       449
   macro avg       0.98      0.98      0.98       449
weighted avg       0.98      0.98      0.98       449

